a=int(input("Input real part of first complex no. "))
b=int(input("Input imaginary part of first complex no. "))
c=int(input("Input real part of second complex no. "))
d = int(input("Input imaginary part of second complex no. "))
z1=complex(a,b)
z2=complex(c,d)
print("Sum of two complex number ",z1+z2)